# Nome do executável
TARGET = myprogram

# Compilador e flags
CC = gcc
CFLAGS = -Wall

# Arquivos fonte
SRCS = main.c mymath.c arquivo.c

# Regras para construir o executável
$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)

# Limpeza dos arquivos gerados
